### ISSUE TITLE
assertions.Equal add `using_key`

### ISSUE THREAD

**Issue by dmicanzerofox** [dm03514/func-y-task-engine#56]
Allows for assertions.Equal to be applied to a dictionary

https://github.com/dm03514/func-y-task-engine/blob/master/funcytaskengine/transition_conditions/assertions.py#L77

```
transition_conditions:
  - type: assertions.Equal
     using_key: returncode
     to_equal: 0
```

```
class Equal(BaseTransitionCondition):
    def __init__(self, type, to_equal, value_property=None, using_key=None):
        self.value_property = value_property
        self.to_equal = to_equal
        self.using_key = using_key

    def apply(self, vs):
        for v in vs.values():
            to_assert = v
            if self.value_property:
                to_assert = getattr(v, self.value_property)
            if self.using_key:
                to_assert = v[self.using_key]
            assert self.to_equal == to_assert, '{} != {}'.format(self.to_equal, to_assert)
        return vs
```
